name: Infralovers Changelog Automation

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  changelog-automation:
    uses: infralovers/.github/.github/workflows/changelog-automation.yml@main
    secrets: inherit
