name: Infralovers Container Build

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]


jobs:
  build:
    uses: infralovers/.github/.github/workflows/container.yml@main
    secrets: inherit
    env:
      platforms: linux/amd64, linux/arm64

      QUAY_USER: "${{ fromJSON(secrets.VAULT_KV_1D187965_OP_QUAY_ROBOT_ACCOUNT).username }}"
      QUAY_TOKEN: "${{ fromJSON(secrets.VAULT_KV_1D187965_OP_QUAY_ROBOT_ACCOUNT).password }}"

      BOT_ACCESS_TOKEN: "${{ fromJSON(secrets.VAULT_KV_1D187965_OP_GITHUB_INFRALOVERS).PAT }}"
