---
name: 'Validate PR template'

on:
  # pull_request_target:
  #   types:
  #     - opened
  #     - edited
  #     - synchronize

  workflow_call:
    secrets:
      BOT_ACCESS_TOKEN:
        description: 'The GitHub token for the bot account'
        required: true

permissions:
  pull-requests: write
  statuses: write

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      # Please look up the latest version from
      # https://github.com/amannn/action-semantic-pull-request/releases
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
        with:
          types: |
            fix
            feat
            docs
            ci
            chore

          requireScope: false
          subjectPattern: ^.+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            starts with an uppercase character.
          wip: true
          validateSingleCommit: false
