name: 'Validate PR title'

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize


jobs:
  changelog-automation:
    uses: ./workflows/pre-validation.yml@main
    secrets: inherit
    