---

name: 'Validate PR'

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - assigned


jobs:
  pr-validation:
    uses: ./.github/workflows/pr-validation.yml
    secrets: inherit
