name: 'Validate PR title'

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize


jobs:
  changelog-automation:
    uses: ./.github/workflows/pre-validation.yml
    secrets: inherit
