---

name: 'Validate PR'

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - assigned


permissions:
  pull-requests: write
  statuses: write


jobs:
  pr-validation:
    uses: ./.github/workflows/pr-validation.yml
    secrets:
      BOT_ACCESS_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
